version: '3.8'

services:
  chatty-redis:
    image: redis:alpine
    networks:
      - chat-net

  chatty-mongo:
    image: mongo:latest
    volumes:
      - chatty-db:/data/db
    networks:
      - chat-net

  chatty-server:
    build: .
    image: chat-server:latest
    deploy:
      replicas: 2
    environment:
      - PORT=3000
      - REDIS_HOST=chatty-redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://chatty-mongo:27017/chat-db
    networks:
      - chat-net
    depends_on:
      - chatty-redis
      - chatty-mongo

  chatty-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - chat-net
    depends_on:
      - chatty-server

networks:
  chat-net:
    driver: bridge

volumes:
  chatty-db:
